pluginManagement {
    includeBuild 'build-logic'
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    plugins {
        id 'com.google.protobuf' version '0.9.6'
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'pocketpick'

include 'service-user'
include 'services:order'
