plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal()
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-gradle-plugin:4.1.0'
    implementation 'io.spring.gradle:dependency-management-plugin:1.1.7'
    implementation 'com.google.protobuf:protobuf-gradle-plugin:0.9.6'
}
