plugins {
    id 'pocketpick.java-conventions'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2025.1.2"
    }
}

jar { enabled = false }
bootJar { enabled = true }
